[linux] add rootless build
LibreELEC/usb-sd-creator pull request #29
Opened 2023-07-06 05:34 UTC by lrusak

This does a few things.
 - Creates an initial CMake build. This is now the standard in Qt6 instead of qmake. This is likely not working properly for Windows or MacOS builds at this time.
 - Adds a linux build that uses UDisks2 via dbus. This allows the application to run rootless and will prompt for an administrator password (through UDisks2 interactive authentication).
 - Adds a github actions build for the new linux build.
 - Cleans up the linux helper scripts to use the new CMake build.

The rootless build is needed to be able to run on wayland.

2024-02-15 17:00 UTC, kambala-decapitator requested changes

2024-02-15 17:00 UTC, kambala-decapitator commented on CMakeLists.txt
> +        -Ic:\Qt\Qt5.6.1\Tools\mingw492_32\i686-w64-mingw32\include
nice :)

2024-02-15 17:00 UTC, kambala-decapitator commented on CMakeLists.txt
> +qt_add_executable(LibreELEC.USB-SD.Creator WIN32 MACOSX_BUNDLE
I'd use a shorter target name

2024-02-15 17:00 UTC, kambala-decapitator commented on CMakeLists.txt
> +endif()
what is this for?

2024-02-15 17:00 UTC, kambala-decapitator commented on CMakeLists.txt
> +if(LINUX)
New in version 3.25.

2024-02-15 17:00 UTC, kambala-decapitator commented on creator.cpp
> +#ifdef Q_OS_MAC
what about BSD?

2024-02-15 17:00 UTC, kambala-decapitator commented on creator.h
> +#ifdef Q_OS_MAC
what about BSD?

2024-02-15 17:00 UTC, kambala-decapitator commented on diskwriter_udisks2.h
> +    Q_OBJECT
the macro shouldn't be needed as you don't have any signals

2024-02-15 17:00 UTC, kambala-decapitator commented on main.cpp
> +#ifdef Q_OS_MAC
what about BSD?

2024-02-15 17:17 UTC, chewitt commented
@kambala-decapitator there are no plans to support the app on BSD

2024-02-15 17:28 UTC, kambala-decapitator commented
funny, I can't resolve my own conversations :)

> @kambala-decapitator there are no plans to support the app on BSD

clear, thanks!

2024-02-15 22:56 UTC, fuzzard commented on CMakeLists.txt
> +    find_package(Qt${QT_VERSION_MAJOR} REQUIRED COMPONENTS DBus)
Ill mention, but i dont have references off hand, however multiple find_package calls to the same thing (ie Qt${QT_VERSION_MAJOR}) wont actually work.

The way the caching of find_package works, it essentially wont change anything after its called once.

Youd be better making the linux check early, and adding a variable for this to the initial call.

2024-02-15 23:37 UTC, lrusak commented
Just an FYI for those interested. In the OP it does say:
> This is likely not working properly for Windows or MacOS builds at this time.

2024-02-18 07:37 UTC, kambala-decapitator commented
we can merge as is and provide adjustments in the following PRs

2024-02-18 08:58 UTC, merged